name: Build and Deploy README as GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write  # Adjusted to write to allow pushing to gh-pages.
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Use an appropriate Ruby version

      - name: Install Jekyll
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build site
        run: |
          # Assuming README.md is renamed to index.md or configured via _config.yml
          jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
